export default {
  'pt-BR': {
    sectionName: 'contato',
    name: 'nome *',
    name_error_required: "'nome' é obrigatório",
    name_error_length: "'nome' deve ter entre 1-32 caracteres",
    lastName: 'sobrenome *',
    lastName_error_required: "'sobrenome' é obrigatório",
    lastName_error_length: "'sobrenome' deve ter entre 1-32 caracteres",
    email: 'e-mail *',
    email_error_required: "'email' é obrigatório",
    subject: 'assunto *',
    subject_error_required: "'assunto' é obrigatório",
    subject_error_length: "'assunto' deve ter entre 1-96 caracteres",
    message: 'mensagem *',
    message_error_required: "'mensagem' é obrigatório",
    message_error_length: "'mensagem' deve ter entre 1-2048 caracteres",
    button: 'enviar',
  },
  'en-US': {
    sectionName: 'contact',
    name: 'name *',
    name_error_required: "'name' is required",
    name_error_length: "'name' must contain between 1-32 characters",
    lastName: 'last name *',
    lastName_error_required: "'last name' is required",
    lastName_error_length: "'last name' must contain between 1-32 characters",
    email: 'e-mail *',
    email_error_required: "'email' is required",
    subject: 'subject *',
    subject_error_required: "'subject' is required",
    subject_error_length: "'subject' must contain between 1-96 characters",
    message: 'message *',
    message_error_required: "'message' is required",
    message_error_length: "'message' must contain between 1-4096 characters",
    button: 'send',
  },
};
